### ISSUE TITLE
Update HTML to reflect hydration and sleep data outputs

### ISSUE THREAD

**Issue by crotteau** [AsherSpurr/fitlit#8]
We have more data we want to display on the DOM than what we originally planned for in our comp. Therefore, we need to update our html so we can view all the necessary weekly data. 

As a user, when I visit the FitLit page, I want to see all of the previous week's hydration and CSS data, so that it's more comprehensive than a single average.

**Comment by AsherSpurr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create HTML](https://trello.com/c/zy0BxQ7G/22-create-html)
